### ISSUE TITLE
Error during list generation: 'PolarAxesSubplot' object is not iterable

### ISSUE THREAD

**Issue by don-vip** [rixx/city-street-orientations#2]
I'm running the script on Windows, Python 3.7.0, Matplotlib 2.2.2 with the following data:

```json
{
    "Toulouse": {"city": "Toulouse"}
}
```

I can't make it work, I always face error message "Error during list generation: 'PolarAxesSubplot' object is not iterable.".

I see this statement returns `PolarAxesSubplot(0.125,0.11;0.775x0.77)` in `axes` instead of an iterable but I don't know how to fix it:

```python
    fig, axes = plt.subplots(
        nrows, ncols, figsize=figsize,
        subplot_kw={'projection': 'polar'},
    )
```

**Comment by rixx** [comment]
This issue occurs if you want to generate a list with only one polar plot. The original IPython notebook had the same issue – I'm not really keen on solving it, especially since my script offers you single city generation as an alternative instead.

**Comment by don-vip** [comment]
OK thanks!
